plugin:
  name: custom-data-type-iucn
  version: 1.0
  url: https://github.com/programmfabrik/easydb-custom-data-type-iucn
  displayname:
    de-DE: IUCN
    en-US: IUCN
  info:
    de-DE: IUCN
    en-US: IUCN
  server:
    api-version:
      require: 1
  webfrontend:
    url: custom-data-type-iucn.js
    css: custom-data-type-iucn.css
    logo: image/logo.png
    l10n: l10n/

custom_types:
  iucn:
    update:
      script: build/scripts/iucn-update.js
      timeout: 10
      batch_size: 1000
      interval_base_config: update_interval_iucn.days
      easydb_api_url: http://127.0.0.1/api/v1
    mapping:
      idTaxon:
        type: text_oneline
      scientificName:
        type: text
      mainCommonName:
        type: text

base_config:
  - name: iucn_api_settings
    group: iucn
    parameters:
      api_url:
        type: text
        position: 0
      api_token:
        type: text
        position: 1
  - name: iucn_easydb_settings
    group: iucn
    parameters:
      easydb_login:
        type: text
        position: 0
      easydb_password:
        type: text
        position: 1
  - name: iucn_settings
    group: iucn
    parameters:
      tag_red:
        type: int
        position: 0
        plugin_type: "iucn_tag"
      tag_unclear:
        type: int
        position: 1
        plugin_type: "iucn_tag"
      iucn_fields:
        type: table
        position: 2
        fields:
          - name: iucn_field_name
            type: text
            position: 0
            plugin_type: "iucn_field_name"

